package leetcode_strings;

import java.util.ArrayList;

public class Question15 {

    /*
    You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
     */

    public static char findTheDifference(String s, String t) {
        if (s.length() == 0 && s.toLowerCase().equals(s.toUpperCase())) {
            return t.charAt(0);
        }
        ArrayList<Character> check = new ArrayList<>();
        for (Character ch : t.toCharArray()) {
            check.add(ch);
        }

        for (Character ch : s.toCharArray()
        ) {
            check.remove(ch);
        }
        return check.get(0);
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "abcde"));
        System.out.println(findTheDifference("", "y"));
    }
}
